import PptxGenJS from "pptxgenjs";

export async function POST(req: Request) {
  const { topic, slidesCount, tone } = await req.json();

  try {
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "meta-llama/llama-3-8b-instruct",
        messages: [
          {
            role: "system",
            content: "You are a professional presentation creator.",
          },
          {
            role: "user",
            content: `Create a PowerPoint presentation about "${topic}".

Generate EXACTLY ${slidesCount} slides.

Each slide must:
- Have a short, clear title
- Include 3 concise bullet points (max 12 words each)
- Avoid repetition
- Focus on different aspects (definition, applications, benefits, challenges, future)

Write in ${tone} tone.

Format:

Slide 1: Title
- point
- point
- point.

Generate EXACTLY ${slidesCount} slides.

Format:

Slide 1: Title
- point
- point
- point

Rules:
- Make content detailed and meaningful
- Avoid generic phrases
- Each point must explain something useful`,
          },
        ],
      }),
    });

    const data = await res.json();

    const text = data.choices?.[0]?.message?.content || "";

    // 🧠 Parse slides
    const slideBlocks = text
      .split("Slide ")
      .slice(1, slidesCount + 1);

    const slides = slideBlocks.map((block: string) => {
      const lines = block.split("\n").filter((l) => l.trim() !== "");

      return {
        title: lines[0]
          .replace(/^(\d+:)?/g, "")     // remove "1:"
          .replace(/^Slide\s*/i, "")    // remove "Slide"
          .replace(/^Title:\s*/i, "")   // remove "Title:"
          .trim(),
        points: lines
          .slice(1)
          .map((p) => p.replace(/^[-•\d. ]+/, "").trim())
          .filter((p) => p.length > 0 && p.length < 120) // 👈 LIMIT LENGTH
          .slice(0, 3)
      };
    });

    // 🎯 Create PPT
    const pptx = new PptxGenJS();

    // 🎯 Add title slide
const firstSlide = pptx.addSlide();

firstSlide.background = { fill: "0F172A" };

firstSlide.addText(topic, {
  x: 0.5,
  y: 1.8,
  w: "90%",
  align: "center",
  fontSize: 40,
  bold: true,
  color: "38BDF8",
});
firstSlide.addText("Generated by AI Presentation Builder", {
  x: 0.5,
  y: 3,
  w: "90%",
  align: "center",
  fontSize: 18,
  color: "E2E8F0",
});

    slides.forEach((slideData: { title: string; points: string[] }) => {
  const slide = pptx.addSlide();

  // 🎨 Background
  slide.background = { fill: "0F172A" };

  // 🧠 Title (centered)
  slide.addText(slideData.title, {
    x: 0.5,
    y: 0.6,
    w: "90%",
    h: 1,
    align: "center",
    fontSize: 32,
    bold: true,
    color: "38BDF8",
  });

  // 🎨 Divider line
  slide.addShape("rect", {
    x: 1,
    y: 1.5,
    w: 8,
    h: 0.08,
    fill: { color: "38BDF8" },
  });

  // 🧠 Content (aligned properly)
  // 🧠 Content (aligned properly)
slide.addText(
  Array.isArray(slideData.points)
    ? slideData.points.join("\n")
    : slideData.points,
  {
    x: 1.2,
    y: 2,
    w: 6.5,
    h: 3,
    fontSize: 20,
    color: "E2E8F0",
    bullet: true,
    lineSpacing: 32,
  }
);
});

    const buffer = await pptx.write({ outputType: "base64" });

    return Response.json({
      file: buffer,
      slides: slides,
    });

  } catch (error) {
    console.error(error);

    return Response.json({
      error: "AI generation failed",
    });
  }
}